/**
 * COLOR AI MODULE — now backed by the real trained model at ../../backend.
 * extractDominantColors and generatePalette call the FastAPI service.
 * Everything else here (tint ramp, hover reroll, brand palette) is
 * unrelated client-side UI logic and is unchanged.
 */

const API_URL = "http://localhost:8000";

/**
 * A large, hue-diverse "pretty color" pool (100 colors).
 * Generated by walking the hue wheel in golden-angle steps (~137.5°) so
 * consecutive entries land far apart on the color wheel — no clusters of
 * similar shades — while saturation/lightness are gently varied per entry
 * to keep every color looking intentional rather than random/muddy.
 */
function buildBrandPalette(count: number): string[] {
  const GOLDEN_ANGLE = 137.508;
  const out: string[] = [];
  let hue = 18;
  for (let i = 0; i < count; i++) {
    const s = 62 + ((i * 7) % 30); // 62–92% saturation
    const l = 48 + ((i * 11) % 24); // 48–72% lightness
    out.push(hslToHex(hue, s, l));
    hue = (hue + GOLDEN_ANGLE) % 360;
  }
  return out;
}

export const BRAND_PALETTE = buildBrandPalette(100);

export type Category =
  | "Graphic Design"
  | "UI/UX"
  | "fashion"
  | "Interior home design";

// UI label -> API category code
const CATEGORY_CODE: Record<Category, string> = {
  "Graphic Design": "graphic_design",
  "UI/UX": "uiux",
  fashion: "fashion",
  "Interior home design": "home_interior",
};

/* ------------------------------- color utils ------------------------------ */

export function hexToRgb(hex: string) {
  const h = hex.replace("#", "");
  const full =
    h.length === 3
      ? h
          .split("")
          .map((c) => c + c)
          .join("")
      : h;
  return {
    r: parseInt(full.slice(0, 2), 16),
    g: parseInt(full.slice(2, 4), 16),
    b: parseInt(full.slice(4, 6), 16),
  };
}

export function rgbToHex(r: number, g: number, b: number) {
  const t = (n: number) =>
    Math.max(0, Math.min(255, Math.round(n))).toString(16).padStart(2, "0");
  return `#${t(r)}${t(g)}${t(b)}`.toUpperCase();
}

export function rgbToHsl(r: number, g: number, b: number) {
  r /= 255;
  g /= 255;
  b /= 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  let h = 0;
  const l = (max + min) / 2;
  const d = max - min;
  const s = d === 0 ? 0 : d / (1 - Math.abs(2 * l - 1));
  if (d !== 0) {
    if (max === r) h = ((g - b) / d) % 6;
    else if (max === g) h = (b - r) / d + 2;
    else h = (r - g) / d + 4;
    h *= 60;
    if (h < 0) h += 360;
  }
  return { h, s: s * 100, l: l * 100 };
}

export function hslToHex(h: number, s: number, l: number) {
  const sn = Math.max(0, Math.min(100, s)) / 100;
  const ln = Math.max(0, Math.min(100, l)) / 100;
  const c = (1 - Math.abs(2 * ln - 1)) * sn;
  const hp = (((h % 360) + 360) % 360) / 60;
  const x = c * (1 - Math.abs((hp % 2) - 1));
  let [r, g, b] = [0, 0, 0];
  if (hp < 1) [r, g, b] = [c, x, 0];
  else if (hp < 2) [r, g, b] = [x, c, 0];
  else if (hp < 3) [r, g, b] = [0, c, x];
  else if (hp < 4) [r, g, b] = [0, x, c];
  else if (hp < 5) [r, g, b] = [x, 0, c];
  else [r, g, b] = [c, 0, x];
  const m = ln - c / 2;
  return rgbToHex((r + m) * 255, (g + m) * 255, (b + m) * 255);
}

export function hexToHsl(hex: string) {
  const { r, g, b } = hexToRgb(hex);
  return rgbToHsl(r, g, b);
}

/** Pick readable foreground text for a background color. */
export function readableTextOn(hex: string) {
  const { r, g, b } = hexToRgb(hex);
  const lum = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
  return lum > 0.6 ? "#0B0B0B" : "#F5F5F5";
}

/* --------------------------- extraction (real API) ------------------------ */
/**
 * Sends the image to the trained backend, gets back candidate colors found
 * in it, to fill the "colors extracted from the image" swatch row.
 */
export async function extractDominantColors(
  file: File,
  _count = 6,
): Promise<string[]> {
  const form = new FormData();
  form.append("image", file);

  const res = await fetch(`${API_URL}/extract-colors`, {
    method: "POST",
    body: form,
  });
  if (!res.ok) throw new Error("extract-colors failed");
  const data = await res.json();
  return data.colors as string[];
}

/* --------------------------- MOCK: tint ramp ------------------------------ */
/** Lightness ramp of a single color, lightest -> darkest. (Client-side only,
 * unrelated to the trained model — unchanged.) */
export function generateTintRamp(hex: string, count = 6): string[] {
  const { h, s } = hexToHsl(hex);
  const top = 90;
  const bottom = 15;
  if (count <= 1) return [hslToHex(h, s, 50)];
  return Array.from({ length: count }, (_, i) =>
    hslToHex(h, s, top - ((top - bottom) * i) / (count - 1)),
  );
}

/* ------------------------ field palette (real API) ------------------------ */
/**
 * Sends the picked color + category to the trained backend, gets back a
 * rule-based palette (pure color theory — no dataset, no retrieval): the
 * picked color plus however many companions that category's rules
 * produce (5 for graphic_design/home_interior/fashion, 6 for uiux). Each
 * color carries a real, rule-derived label — not a fabricated role.
 */
export type PaletteColor = { hex: string; label: string; note?: string };
export type PaletteResult = {
  palette: PaletteColor[];
  summary: Record<string, string>;
};

export async function generatePalette(
  pickedColor: string,
  category: Category,
  variation = 0,
): Promise<PaletteResult> {
  const form = new FormData();
  form.append("base_color", pickedColor);
  form.append("category", CATEGORY_CODE[category]);
  form.append("variation", String(variation));

  const res = await fetch(`${API_URL}/generate-palette`, {
    method: "POST",
    body: form,
  });
  if (!res.ok) throw new Error("generate-palette failed");
  const data = await res.json();
  return { palette: data.palette as PaletteColor[], summary: data.summary };
}

/**
 * Hover reroll: picks a brand color that is meaningfully different from the
 * current one — filtered by hue distance (not just a different hex) so a
 * reroll never lands on another shade of the same color.
 */
export function nextHoverColor(current: string): string {
  const { h: currentHue } = hexToHsl(current);
  const farEnough = (hex: string) => {
    const { h } = hexToHsl(hex);
    const diff = Math.abs(h - currentHue);
    return Math.min(diff, 360 - diff) > 40;
  };

  const pool = BRAND_PALETTE.filter(farEnough);
  const candidates = pool.length > 0 ? pool : BRAND_PALETTE;
  return candidates[Math.floor(Math.random() * candidates.length)]!;
}
